---
abstract: 'Patrons Account Information API command line client'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PAIA
recommends:
  Mozilla::CA: 0
requires:
  App::Cmd: 0.322
  HTTP::Tiny: 0.024
  IO::Socket::SSL: 1.56
  JSON::PP: 2.27103
  Net::SSLeay: 1.49
  URI: 1.59
  perl: v5.10.0
resources:
  bugtracker: https://github.com/gbv/App-PAIA/issues
  homepage: https://github.com/gbv/App-PAIA
  repository: https://github.com/gbv/App-PAIA.git
version: 0.27
