---
abstract: 'Patrons Account Information API command line client'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PAIA
requires:
  App::Cmd: 0.314
  IO::Socket::SSL: 1.56
  Net::SSLeay: 1.49
resources:
  bugtracker: https://github.com/gbv/App-PAIA/issues
  homepage: https://github.com/gbv/App-PAIA
  repository: https://github.com/gbv/App-PAIA.git
version: 0.01
